"""empty message

Revision ID: ace0e3522199
Revises: 
Create Date: 2020-05-26 09:25:22.530017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace0e3522199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cannabis',
    sa.Column('strain_index', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('strain_name', sa.String(), nullable=True),
    sa.Column('strain_type', sa.String(), nullable=True),
    sa.Column('strain_rating', sa.String(), nullable=True),
    sa.Column('effect_profile', sa.String(), nullable=True),
    sa.Column('flavor_profile', sa.String(), nullable=True),
    sa.Column('strain_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.drop_table('Cannabis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cannabis',
    sa.Column('strain_index', sa.TEXT(), nullable=True),
    sa.Column('model_id', sa.TEXT(), nullable=True),
    sa.Column('strain_name', sa.TEXT(), nullable=True),
    sa.Column('strain_type', sa.TEXT(), nullable=True),
    sa.Column('strain_rating', sa.TEXT(), nullable=True),
    sa.Column('effect_profile', sa.TEXT(), nullable=True),
    sa.Column('flavor_profile', sa.TEXT(), nullable=True),
    sa.Column('strain_description', sa.TEXT(), nullable=True)
    )
    op.drop_table('cannabis')
    # ### end Alembic commands ###
